// This file is a part of muu and is subject to the the terms of the MIT license.
// Copyright (c) 2020 Mark Gillard <mark.gillard@outlook.com.au>
// See https://github.com/marzer/muu/blob/master/LICENSE for the full license text.
// SPDX-License-Identifier: MIT
//-----
// this file was generated by generate_unicode_functions.py - do not modify it directly

#include "tests.h"
#include "unicode.h"
#include "../include/muu/strings.h"

TEST_CASE("unicode - is_ascii_code_point (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_ascii_code_point);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ '\0', '\x7F' },
	};
	for (const auto& r : true_ranges)
	{
		REQUIRE(in(fn, r));
		REQUIRE(in_only<1>(fn, r));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x80u, 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_ascii_hyphen (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_ascii_hyphen);
 
	// values which should return true
	static constexpr char true_values[] = 
	{
		'-',
	};
	for (auto v : true_values)
	{
		REQUIRE(fn(v));
		REQUIRE(in_only<2>(fn, v));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', ',' }, { '.', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_ascii_letter (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_ascii_letter);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ 'A', 'Z' }, { 'a', 'z' },
	};
	for (const auto& r : true_ranges)
	{
		REQUIRE(in(fn, r));
		REQUIRE(in_only<3>(fn, r));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', '@' }, { '[', '`' }, { '{', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_ascii_lowercase (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_ascii_lowercase);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ 'a', 'z' },
	};
	for (const auto& r : true_ranges)
	{
		REQUIRE(in(fn, r));
		REQUIRE(in_only<6>(fn, r));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', '`' }, { '{', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_ascii_number (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_ascii_number);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ '0', '9' },
	};
	for (const auto& r : true_ranges)
	{
		REQUIRE(in(fn, r));
		REQUIRE(in_only<4>(fn, r));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', '/' }, { ':', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_ascii_uppercase (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_ascii_uppercase);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ 'A', 'Z' },
	};
	for (const auto& r : true_ranges)
	{
		REQUIRE(in(fn, r));
		REQUIRE(in_only<7>(fn, r));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', '@' }, { '[', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_ascii_whitespace (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_ascii_whitespace);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ '\t', '\r' },
	};
	for (const auto& r : true_ranges)
	{
		REQUIRE(in(fn, r));
		REQUIRE(in_only<5>(fn, r));
	}
	static constexpr char true_values[] = 
	{
		' ',
	};
	for (auto v : true_values)
	{
		REQUIRE(fn(v));
		REQUIRE(in_only<5>(fn, v));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', '\b' }, { '\x0E', '\x1F' }, { '!', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_non_ascii_code_point (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_non_ascii_code_point);
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_non_ascii_hyphen (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_non_ascii_hyphen);
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_non_ascii_letter (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_non_ascii_letter);
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_non_ascii_lowercase (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_non_ascii_lowercase);
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_non_ascii_number (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_non_ascii_number);
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_non_ascii_uppercase (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_non_ascii_uppercase);
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_non_ascii_whitespace (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_non_ascii_whitespace);
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_code_point (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_code_point);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ '\0', '\x7F' },
	};
	for (const auto& r : true_ranges)
		REQUIRE(in(fn, r));
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x80u, 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_combining_mark (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_combining_mark);
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_decimal_digit (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_decimal_digit);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ '0', '9' },
	};
	for (const auto& r : true_ranges)
		REQUIRE(in(fn, r));
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', '/' }, { ':', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_hexadecimal_digit (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_hexadecimal_digit);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ '0', '9' }, { 'A', 'F' }, { 'a', 'f' },
	};
	for (const auto& r : true_ranges)
		REQUIRE(in(fn, r));
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', '/' }, { ':', '@' }, { 'G', '`' },
		{ 'g', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_octal_digit (char)")
{
	static constexpr auto fn = static_cast<code_unit_func<char>*>(is_octal_digit);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ '0', '7' },
	};
	for (const auto& r : true_ranges)
		REQUIRE(in(fn, r));
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ '\0', '/' }, { '8', 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

template <>
struct code_unit_func_group<char, 1>
{
	static constexpr code_unit_func<char>* functions[] =
	{
		is_ascii_code_point,
		is_non_ascii_code_point,
		is_not_code_point,
	};
};

template <>
struct code_unit_func_group<char, 2>
{
	static constexpr code_unit_func<char>* functions[] =
	{
		is_ascii_hyphen,
		is_non_ascii_hyphen,
		is_not_hyphen,
	};
};

template <>
struct code_unit_func_group<char, 3>
{
	static constexpr code_unit_func<char>* functions[] =
	{
		is_ascii_letter,
		is_non_ascii_letter,
		is_not_letter,
	};
};

template <>
struct code_unit_func_group<char, 4>
{
	static constexpr code_unit_func<char>* functions[] =
	{
		is_ascii_number,
		is_non_ascii_number,
		is_not_number,
	};
};

template <>
struct code_unit_func_group<char, 5>
{
	static constexpr code_unit_func<char>* functions[] =
	{
		is_ascii_whitespace,
		is_non_ascii_whitespace,
		is_not_whitespace,
	};
};

template <>
struct code_unit_func_group<char, 6>
{
	static constexpr code_unit_func<char>* functions[] =
	{
		is_ascii_lowercase,
		is_non_ascii_lowercase,
		is_not_lowercase,
	};
};

template <>
struct code_unit_func_group<char, 7>
{
	static constexpr code_unit_func<char>* functions[] =
	{
		is_ascii_uppercase,
		is_non_ascii_uppercase,
		is_not_uppercase,
	};
};

