// This file is a part of muu and is subject to the the terms of the MIT license.
// Copyright (c) 2020 Mark Gillard <mark.gillard@outlook.com.au>
// See https://github.com/marzer/muu/blob/master/LICENSE for the full license text.
// SPDX-License-Identifier: MIT
//-----
// this file was generated by generate_unicode_functions.py - do not modify it directly

#include "tests.h"

#ifndef __cpp_char8_t

#include "unicode.h"
#include "../include/muu/strings.h"

TEST_CASE("unicode - is_ascii (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_ascii);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ 0x00u, 0x7Fu },
	};
	for (const auto& r : true_ranges)
	{
		REQUIRE(in(fn, r));
		REQUIRE(in_only<1>(fn, r));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x80u, 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_unicode (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_unicode);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ 0x80u, 0xFFu },
	};
	for (const auto& r : true_ranges)
	{
		REQUIRE(in(fn, r));
		REQUIRE(in_only<1>(fn, r));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x00u, 0x7Fu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_ascii_whitespace (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_ascii_whitespace);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ 0x09u, 0x0Du },
	};
	for (const auto& r : true_ranges)
	{
		REQUIRE(in(fn, r));
		REQUIRE(in_only<2>(fn, r));
		REQUIRE(in_only<7>(fn, r));
	}
	static constexpr unsigned char true_values[] = 
	{
		0x20u,
	};
	for (auto v : true_values)
	{
		REQUIRE(fn(v));
		REQUIRE(in_only<2>(fn, v));
		REQUIRE(in_only<7>(fn, v));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x00u, 0x08u }, { 0x0Eu, 0x1Fu }, { 0x21u, 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_unicode_whitespace (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_unicode_whitespace);
 
	// values which should return true
	static constexpr unsigned char true_values[] = 
	{
		0x85u, 0xA0u,
	};
	for (auto v : true_values)
	{
		REQUIRE(fn(v));
		REQUIRE(in_only<2>(fn, v));
		REQUIRE(in_only<7>(fn, v));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x00u, 0x84u }, { 0x86u, 0x9Fu }, { 0xA1u, 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_ascii_letter (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_ascii_letter);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ 0x41u, 0x5Au }, { 0x61u, 0x7Au },
	};
	for (const auto& r : true_ranges)
	{
		REQUIRE(in(fn, r));
		REQUIRE(in_only<3>(fn, r));
		REQUIRE(in_only<7>(fn, r));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x00u, 0x40u }, { 0x5Bu, 0x60u }, { 0x7Bu, 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_unicode_letter (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_unicode_letter);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ 0xC0u, 0xD6u }, { 0xD8u, 0xF6u }, { 0xF8u, 0xFFu },
	};
	for (const auto& r : true_ranges)
	{
		REQUIRE(in(fn, r));
		REQUIRE(in_only<3>(fn, r));
		REQUIRE(in_only<7>(fn, r));
	}
	static constexpr unsigned char true_values[] = 
	{
		0xAAu, 0xB5u, 0xBAu,
	};
	for (auto v : true_values)
	{
		REQUIRE(fn(v));
		REQUIRE(in_only<3>(fn, v));
		REQUIRE(in_only<7>(fn, v));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x00u, 0xA9u }, { 0xABu, 0xB4u }, { 0xB6u, 0xB9u },
		{ 0xBBu, 0xBFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
	static constexpr unsigned char false_values[] = 
	{
		0xD7u, 0xF7u,
	};
	for (auto v : false_values)
		REQUIRE(!fn(v));
}

TEST_CASE("unicode - is_ascii_number (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_ascii_number);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ 0x30u, 0x39u },
	};
	for (const auto& r : true_ranges)
	{
		REQUIRE(in(fn, r));
		REQUIRE(in_only<4>(fn, r));
		REQUIRE(in_only<7>(fn, r));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x00u, 0x2Fu }, { 0x3Au, 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_unicode_number (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_unicode_number);
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x00u, 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_ascii_hyphen (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_ascii_hyphen);
 
	// values which should return true
	static constexpr unsigned char true_values[] = 
	{
		0x2Du,
	};
	for (auto v : true_values)
	{
		REQUIRE(fn(v));
		REQUIRE(in_only<5>(fn, v));
		REQUIRE(in_only<7>(fn, v));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x00u, 0x2Cu }, { 0x2Eu, 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_unicode_hyphen (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_unicode_hyphen);
 
	// values which should return true
	static constexpr unsigned char true_values[] = 
	{
		0xADu,
	};
	for (auto v : true_values)
	{
		REQUIRE(fn(v));
		REQUIRE(in_only<5>(fn, v));
		REQUIRE(in_only<7>(fn, v));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x00u, 0xACu }, { 0xAEu, 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_combining_mark (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_combining_mark);
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x00u, 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_octal_digit (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_octal_digit);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ 0x30u, 0x37u },
	};
	for (const auto& r : true_ranges)
		REQUIRE(in(fn, r));
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x00u, 0x2Fu }, { 0x38u, 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_decimal_digit (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_decimal_digit);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ 0x30u, 0x39u },
	};
	for (const auto& r : true_ranges)
		REQUIRE(in(fn, r));
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x00u, 0x2Fu }, { 0x3Au, 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_hexadecimal_digit (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_hexadecimal_digit);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ 0x30u, 0x39u }, { 0x41u, 0x46u }, { 0x61u, 0x66u },
	};
	for (const auto& r : true_ranges)
		REQUIRE(in(fn, r));
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x00u, 0x2Fu }, { 0x3Au, 0x40u }, { 0x47u, 0x60u },
		{ 0x67u, 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
}

TEST_CASE("unicode - is_uppercase (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_uppercase);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ 0x41u, 0x5Au }, { 0xC0u, 0xD6u }, { 0xD8u, 0xDEu },
	};
	for (const auto& r : true_ranges)
	{
		REQUIRE(in(fn, r));
		REQUIRE(in_only<6>(fn, r));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x00u, 0x40u }, { 0x5Bu, 0xBFu }, { 0xDFu, 0xFFu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
	static constexpr unsigned char false_values[] = 
	{
		0xD7u,
	};
	for (auto v : false_values)
		REQUIRE(!fn(v));
}

TEST_CASE("unicode - is_lowercase (unsigned char)")
{
	using namespace impl;
	static constexpr auto fn = static_cast<code_unit_func<unsigned char>*>(is_lowercase);
 
	// values which should return true
	static constexpr code_unit_range<uint32_t> true_ranges[] = 
	{
		{ 0x61u, 0x7Au }, { 0xDFu, 0xF6u }, { 0xF8u, 0xFFu },
	};
	for (const auto& r : true_ranges)
	{
		REQUIRE(in(fn, r));
		REQUIRE(in_only<6>(fn, r));
	}
	static constexpr unsigned char true_values[] = 
	{
		0xAAu, 0xB5u, 0xBAu,
	};
	for (auto v : true_values)
	{
		REQUIRE(fn(v));
		REQUIRE(in_only<6>(fn, v));
	}
 
	// values which should return false
	static constexpr code_unit_range<uint32_t> false_ranges[] = 
	{
		{ 0x00u, 0x60u }, { 0x7Bu, 0xA9u }, { 0xABu, 0xB4u },
		{ 0xB6u, 0xB9u }, { 0xBBu, 0xDEu },
	};
	for (const auto& r : false_ranges)
		REQUIRE(not_in(fn, r));
	static constexpr unsigned char false_values[] = 
	{
		0xF7u,
	};
	for (auto v : false_values)
		REQUIRE(!fn(v));
}

template <>
struct code_unit_func_group<unsigned char, 1>
{
	static constexpr code_unit_func<unsigned char>* functions[] =
	{
		impl::is_ascii,
		impl::is_unicode,
	};
};

template <>
struct code_unit_func_group<unsigned char, 2>
{
	static constexpr code_unit_func<unsigned char>* functions[] =
	{
		impl::is_ascii_whitespace,
		impl::is_unicode_whitespace,
	};
};

template <>
struct code_unit_func_group<unsigned char, 7>
{
	static constexpr code_unit_func<unsigned char>* functions[] =
	{
		impl::is_ascii_hyphen,
		impl::is_ascii_letter,
		impl::is_ascii_number,
		impl::is_ascii_whitespace,
		impl::is_combining_mark,
		impl::is_unicode_hyphen,
		impl::is_unicode_letter,
		impl::is_unicode_number,
		impl::is_unicode_whitespace,
	};
};

template <>
struct code_unit_func_group<unsigned char, 3>
{
	static constexpr code_unit_func<unsigned char>* functions[] =
	{
		impl::is_ascii_letter,
		impl::is_unicode_letter,
	};
};

template <>
struct code_unit_func_group<unsigned char, 4>
{
	static constexpr code_unit_func<unsigned char>* functions[] =
	{
		impl::is_ascii_number,
		impl::is_unicode_number,
	};
};

template <>
struct code_unit_func_group<unsigned char, 5>
{
	static constexpr code_unit_func<unsigned char>* functions[] =
	{
		impl::is_ascii_hyphen,
		impl::is_unicode_hyphen,
	};
};

template <>
struct code_unit_func_group<unsigned char, 6>
{
	static constexpr code_unit_func<unsigned char>* functions[] =
	{
		impl::is_lowercase,
		impl::is_uppercase,
	};
};

#endif // !__cpp_char8_t
