version: 2

jobs:

    debug_clang:
        docker:
            - image: marzer/cpp_dev:0.1.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init --depth 1 external/Catch2
            - run:
                name: Building and testing with clang
                command: |
                    CXX_LD=lld CXX=clang++ meson build --buildtype=debug -Dpedantic=true -Dbuild_tests=true -Db_lto=false
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    release_clang:
        docker:
            - image: marzer/cpp_dev:0.1.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init --depth 1 external/Catch2
            - run:
                name: Building and testing with clang
                command: |
                    CXX_LD=lld CXX=clang++ meson build --buildtype=release -Dpedantic=true -Dbuild_tests=true -Db_lto=false
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    debug_gcc:
        docker:
            - image: marzer/cpp_dev:0.1.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init --depth 1 external/Catch2
            - run:
                name: Building and testing with gcc
                command: |
                    CXX_LD=lld CXX=g++ meson build --buildtype=debug -Dpedantic=true -Dbuild_tests=true -Db_lto=false
                    cd build && meson compile -j 3 && meson test --num-processes 1 --verbose

    release_gcc:
        docker:
            - image: marzer/cpp_dev:0.1.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init --depth 1 external/Catch2
            - run:
                name: Building and testing with gcc
                command: |
                    CXX_LD=lld CXX=g++ meson build --buildtype=release -Dpedantic=true -Dbuild_tests=true -Db_lto=false
                    cd build && meson compile -j 3 && meson test --num-processes 1 --verbose

    generate_dox:
        docker:
            - image: marzer/cpp_dev:0.1.0
        resource_class: small
        steps:
            - checkout
            - run:
                name: Installing dependencies
                command: |
                    pip3 install -r tools/requirements.txt
            - run:
                name: Generating documentation
                command: |
                    cd docs && poxy --verbose
            - persist_to_workspace:
                root: docs
                paths: html

    deploy_dox:
        docker:
            - image: node:14.4.0
        resource_class: small
        steps:
            - checkout
            - attach_workspace:
                at: docs
            - run:
                name: Disable jekyll builds
                command: |
                    touch docs/html/.nojekyll
            - run:
                name: Installing dependencies
                command: |
                    npm install -g --silent gh-pages@3.0.0
                    git config user.email "ci-build@muu.com"
                    git config user.name "ci-build"
            - add_ssh_keys:
                fingerprints:
                    - "7d:0c:c6:80:21:69:dd:e7:6c:c4:07:5b:f6:8f:e0:30"
            - run:
                name: Deploy docs to gh-pages branch
                command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/html

workflows:
    version: 2
    build:
        jobs:
            - debug_clang
            - debug_gcc
            - release_clang
            - release_gcc
            - generate_dox:
                requires:
                    - debug_clang
                    - debug_gcc
                    - release_clang
                    - release_gcc
                filters:
                    branches:
                        only: master
            - deploy_dox:
                requires:
                    - generate_dox
