version: 2

jobs:

    debug_clang_1:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with clang
                command: |
                    CXX_LD=lld CXX=clang++ meson build --buildtype=debug -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=1
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    debug_clang_2:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with clang
                command: |
                    CXX_LD=lld CXX=clang++ meson build --buildtype=debug -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=2
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    debug_clang_3:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with clang
                command: |
                    CXX_LD=lld CXX=clang++ meson build --buildtype=debug -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=3
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    debug_clang_4:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with clang
                command: |
                    CXX_LD=lld CXX=clang++ meson build --buildtype=debug -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=4
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    release_clang_1:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with clang
                command: |
                    CXX_LD=lld CXX=clang++ meson build --buildtype=release -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=1
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    release_clang_2:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with clang
                command: |
                    CXX_LD=lld CXX=clang++ meson build --buildtype=release -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=2
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    release_clang_3:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with clang
                command: |
                    CXX_LD=lld CXX=clang++ meson build --buildtype=release -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=3
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    release_clang_4:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with clang
                command: |
                    CXX_LD=lld CXX=clang++ meson build --buildtype=release -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=4
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    debug_gcc_1:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with gcc
                command: |
                    CXX_LD=lld CXX=g++ meson build --buildtype=debug -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=1
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    debug_gcc_2:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with gcc
                command: |
                    CXX_LD=lld CXX=g++ meson build --buildtype=debug -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=2
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    debug_gcc_3:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with gcc
                command: |
                    CXX_LD=lld CXX=g++ meson build --buildtype=debug -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=3
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    debug_gcc_4:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with gcc
                command: |
                    CXX_LD=lld CXX=g++ meson build --buildtype=debug -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=4
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    release_gcc_1:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with gcc
                command: |
                    CXX_LD=lld CXX=g++ meson build --buildtype=release -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=1
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    release_gcc_2:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with gcc
                command: |
                    CXX_LD=lld CXX=g++ meson build --buildtype=release -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=2
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    release_gcc_3:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with gcc
                command: |
                    CXX_LD=lld CXX=g++ meson build --buildtype=release -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=3
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    release_gcc_4:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: large
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/Catch2
            - run:
                name: Building and testing with gcc
                command: |
                    CXX_LD=lld CXX=g++ meson build --buildtype=release -Dpedantic=true -Dbuild_tests=true -Db_lto=false -Dtest_set=4
                    cd build && meson compile -j 4 && meson test --num-processes 1 --verbose

    generate_dox:
        docker:
            - image: marzer/misc_cpp17_dev:0.2.0
        resource_class: small
        steps:
            - checkout
            - run:
                name: Pulling submodules
                command: |
                    git submodule update --init extern/mcss
            - run:
                name: Generating documentation
                command: |
                    cd python && python3 generate_documentation.py
            - persist_to_workspace:
                root: docs
                paths: html

    deploy_dox:
        docker:
            - image: node:14.4.0
        resource_class: small
        steps:
            - checkout
            - attach_workspace:
                at: docs
            - run:
                name: Disable jekyll builds
                command: |
                    touch docs/html/.nojekyll
            - run:
                name: Installing dependencies
                command: |
                    npm install -g --silent gh-pages@3.0.0
                    git config user.email "ci-build@muu.com"
                    git config user.name "ci-build"
            - add_ssh_keys:
                fingerprints:
                    - "7d:0c:c6:80:21:69:dd:e7:6c:c4:07:5b:f6:8f:e0:30"
            - run:
                name: Deploy docs to gh-pages branch
                command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/html

workflows:
    version: 2
    build:
        jobs:
            - debug_clang_1
            - debug_clang_2
            - debug_clang_3
            - debug_clang_4
            - debug_gcc_1
            - debug_gcc_2
            - debug_gcc_3
            - debug_gcc_4
            - release_clang_1
            - release_clang_2
            - release_clang_3
            - release_clang_4
            - release_gcc_1
            - release_gcc_2
            - release_gcc_3
            - release_gcc_4
            - generate_dox:
                requires:
                    - debug_clang_1
                    - debug_clang_2
                    - debug_clang_3
                    - debug_clang_4
                    - debug_gcc_1
                    - debug_gcc_2
                    - debug_gcc_3
                    - debug_gcc_4
                    - release_clang_1
                    - release_clang_2
                    - release_clang_3
                    - release_clang_4
                    - release_gcc_1
                    - release_gcc_2
                    - release_gcc_3
                    - release_gcc_4
                filters:
                    branches:
                        only: master
            - deploy_dox:
                requires:
                    - generate_dox
