// This file is a part of muu and is subject to the the terms of the MIT license.
// Copyright (c) 2020 Mark Gillard <mark.gillard@outlook.com.au>
// See https://github.com/marzer/muu/blob/master/LICENSE for the full license text.
// SPDX-License-Identifier: MIT
//-----
// this file was generated by generate_unicode_functions.py - do not modify it directly

/// \file
/// \attention These are not the droids you are looking for. Try \ref strings instead.

#pragma once
#include "../../muu/preprocessor.h"
#include MUU_MAKE_STRING(MUU_CONCAT(MUU_CONCAT(../../muu/impl/unicode_char, MUU_WCHAR_BITS), _t.h))

MUU_NAMESPACE_START
{
	/// \brief		Returns true if a wide character is within the ASCII range.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_ascii(wchar_t c) noexcept
	{
		using namespace impl;
		return is_ascii(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is not within the ASCII range (i.e. it is a part greater Unicode).
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_unicode(wchar_t c) noexcept
	{
		using namespace impl;
		return is_unicode(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a whitespace code point from the ASCII range.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_ascii_whitespace(wchar_t c) noexcept
	{
		using namespace impl;
		return is_ascii_whitespace(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a whitespace code point from outside the ASCII range.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_unicode_whitespace(wchar_t c) noexcept
	{
		using namespace impl;
		return is_unicode_whitespace(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a whitespace code point.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_whitespace(wchar_t c) noexcept
	{
		using namespace impl;
		return is_whitespace(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is not a whitespace code point.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_not_whitespace(wchar_t c) noexcept
	{
		using namespace impl;
		return is_not_whitespace(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a letter code point from the ASCII range.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_ascii_letter(wchar_t c) noexcept
	{
		using namespace impl;
		return is_ascii_letter(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a letter code point from outside the ASCII range.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_unicode_letter(wchar_t c) noexcept
	{
		using namespace impl;
		return is_unicode_letter(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a letter code point.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_letter(wchar_t c) noexcept
	{
		using namespace impl;
		return is_letter(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a number code point from the ASCII range.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_ascii_number(wchar_t c) noexcept
	{
		using namespace impl;
		return is_ascii_number(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a number code point from outside the ASCII range.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_unicode_number(wchar_t c) noexcept
	{
		using namespace impl;
		return is_unicode_number(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a number code point.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_number(wchar_t c) noexcept
	{
		using namespace impl;
		return is_number(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a hyphen code point from the ASCII range.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_ascii_hyphen(wchar_t c) noexcept
	{
		using namespace impl;
		return is_ascii_hyphen(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a hyphen code point from outside the ASCII range.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_unicode_hyphen(wchar_t c) noexcept
	{
		using namespace impl;
		return is_unicode_hyphen(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a hyphen code point.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_hyphen(wchar_t c) noexcept
	{
		using namespace impl;
		return is_hyphen(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a combining mark code point.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_combining_mark(wchar_t c) noexcept
	{
		using namespace impl;
		return is_combining_mark(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is an octal digit code point.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_octal_digit(wchar_t c) noexcept
	{
		using namespace impl;
		return is_octal_digit(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a decimal digit code point.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_decimal_digit(wchar_t c) noexcept
	{
		using namespace impl;
		return is_decimal_digit(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a hexadecimal digit code point.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_hexadecimal_digit(wchar_t c) noexcept
	{
		using namespace impl;
		return is_hexadecimal_digit(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is an uppercase code point.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_uppercase(wchar_t c) noexcept
	{
		using namespace impl;
		return is_uppercase(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is an lowercase code point.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_lowercase(wchar_t c) noexcept
	{
		using namespace impl;
		return is_lowercase(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is a code point boundary.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_code_point_boundary(wchar_t c) noexcept
	{
		using namespace impl;
		return is_code_point_boundary(static_cast<wchar_unicode_t>(c));
	}

	/// \brief		Returns true if a wide character is in-and-of-itself a valid code point.
	/// \ingroup	characters
	[[nodiscard]]
	MUU_ALWAYS_INLINE
	MUU_ATTR(const)
	constexpr bool is_code_point(wchar_t c) noexcept
	{
		using namespace impl;
		return is_code_point(static_cast<wchar_unicode_t>(c));
	}

}
MUU_NAMESPACE_END
