name = 'muu'
description = 'Useful utilities for modern C++'
cpp = 17
github = 'marzer/muu'
license = [ 'MIT', 'https://github.com/marzer/muu/blob/master/LICENSE' ]
show_includes = true
generate_tagfile = true
favicon = 'images/favicon.ico'
inline_namespaces = [ 'muu::literals' ]
extra_files = [
	'images/banner.png',
	'images/banner-small.png',
]



[warnings]
enabled = true
treat_as_errors = false
undocumented = false



[meta]
google-site-verification = 'gbtcNgKlNiPSMKkYMw4zWFVWGPH_oU93m9n_-nb4qK8'



[highlighting]
types = [
	'[Mm]y_[a-zA-Z_]+',
	'virtual_base',
	'empty_parent',
	'nonempty_child',
	'immovable',
	'uncopyable'
]
macros = [ 'MUU_[A-Z0-9_]+?' ]
string_literals = [ '_uuid' ]
numeric_literals = [
	'_sz',
	'_[kmg]?b',
	'_[iu](?:8|16|32|64|128)',
	'_f16',
]



[implementation_headers]
'muu/chars.h' = [
	'muu/impl/unicode_char.h',		'muu/impl/unicode_char16_t.h',		'muu/impl/unicode_char32_t.h',
	'muu/impl/unicode_char8_t.h',	'muu/impl/unicode_unsigned_char.h', 'muu/impl/unicode_wchar_t.h'
]



[badges]
'CircleCI' = [ 'https://img.shields.io/circleci/build/github/marzer/muu?label=circle%20ci&logo=circleci&logoColor=white&style=flat-square', 'https://circleci.com/gh/marzer/muu' ]



[autolinks]
'(?:muu::)?halfs?' = 'structmuu_1_1half.html'
'(?:muu::)?matri(?:x|ces)?' = 'structmuu_1_1matrix.html'
'(?:muu::)?string_params?' = 'classmuu_1_1string__param.html'
