namespaces = [
	'muu',
	'muu::literals',
	'muu::impl',
]

inline_namespaces = [
	'muu::literals'
]

types = [
	'bitset',
	'blob',
	'compressed_pair',
	'constants',
	'emplacement_array',
	'half',
	'matrix',
	'quaternion',
	'numeric_range',
	'rolling_average',
	'scope_(?:guard|fail|success)',
	'string_param',
	'tagged_ptr',
	'thread_pool',
	'uuid',

	# documentation example-only types
	'[Mm]y_[a-zA-Z_]+',
	'virtual_base',
	'empty_parent',
	'nonempty_child',
	'immovable',
	'uncopyable'
]

macros = [
	'MUU_[A-Z0-9_]+?'
]

string_literals = [ ]

auto_links = [
	['(?:muu::)?halfs?',          'structmuu_1_1half.html'],
	['(?:muu::)?matri(?:x|ces)?', 'structmuu_1_1matrix.html'],
	['(?:muu::)?string_params?',  'classmuu_1_1string__param.html'],
]

implementation_headers = [
	[
		'muu/chars.h',
		[
			'muu/impl/unicode_char.h',		'muu/impl/unicode_char16_t.h',		'muu/impl/unicode_char32_t.h',
			'muu/impl/unicode_char8_t.h',	'muu/impl/unicode_unsigned_char.h', 'muu/impl/unicode_wchar_t.h'
		],
	],
]

badges = [
	[
		'Releases',
		'https://img.shields.io/github/v/release/marzer/muu?style=flat-square',
		'https://github.com/marzer/muu/releases'
	],
	[
		'C++17',
		'badge-C++17.svg',
		'https://en.cppreference.com/w/cpp/compiler_support'
	],
	[
		'C++20',
		'badge-C++20.svg',
		'https://en.cppreference.com/w/cpp/compiler_support'
	],
	#(None, None, None), # <br>
	[
		'MIT License',
		'badge-license-MIT.svg',
		'https://github.com/marzer/muu/blob/master/LICENSE'
	],
	[
		'CircleCI',
		'https://img.shields.io/circleci/build/github/marzer/muu?label=circle%20ci&logo=circleci&logoColor=white&style=flat-square',
		'https://circleci.com/gh/marzer/muu'
	]
]
