# this is a config file for Poxy - a Doxygen + m.css front-end written in Python.
# https://github.com/marzer/poxy

name                = 'muu'
description         = 'Miscellaneous useful utilities for C++'
cpp                 = 17
github              = 'marzer/muu'
license             = [ 'MIT', 'https://github.com/marzer/muu/blob/master/LICENSE' ]
show_includes       = true
generate_tagfile    = true
logo                = 'images/logo.png'
favicon             = 'images/favicon.ico'
extra_files         = [
    'images/banner.png',
    'images/banner-small.png',
]



[warnings]
enabled             = true
treat_as_errors     = false
undocumented        = false



[sources]
paths               = [ 'pages' ]
recursive_paths     = [ '../include' ]
patterns            = [ '*.h', '*.dox' ]
strip_paths         = [ '../include' ]



[images]
paths               = [ 'images' ]



[code_blocks]
types = [
    '[Mm]y_[a-zA-Z_]+',
    'virtual_base',
    'empty_parent',
    'nonempty_child',
    'immovable',
    'uncopyable'
]
macros = [ 'MUU_[A-Z0-9_]+?' ]
string_literals = [ '_uuid' ]
numeric_literals = [
    '_sz',
    '_[kmg]?b',
    '_[iu](?:8|16|32|64|128)',
    '_f16',
]



[implementation_headers]
'muu/bit.h' = [
    'muu/impl/bit_cast.h'
]
'muu/chars.h' = [
    'muu/impl/unicode_char.h',
    'muu/impl/unicode_char16_t.h',
    'muu/impl/unicode_char32_t.h',
    'muu/impl/unicode_char8_t.h',
    'muu/impl/unicode_unsigned_char.h',
    'muu/impl/unicode_wchar_t.h'
]
'muu/core.h' = [
    'muu/impl/core_build.h',
    'muu/impl/core_constants.h',
    'muu/impl/core_literals.h',
    'muu/impl/core_utils.h'
]

'muu/meta.h' = [
    'muu/impl/is_constant_evaluated.h'
]

'muu/preprocessor.h' = [
    'muu/impl/preprocessor_for_each.h'
]
'muu/strings.h' = [
    'muu/impl/thread_name.h'
]


[badges]
'CircleCI' = [ 'https://circleci.com/gh/marzer/muu.svg?style=shield', 'https://circleci.com/gh/marzer/muu' ]



[autolinks]
'(?:muu::)?halfs?(?!-)' = 'structmuu_1_1half.html'
'(?:muu::)?matri(?:x|ces)?' = 'structmuu_1_1matrix.html'
'(?:muu::)?string_params?' = 'classmuu_1_1string__param.html'
'(?:muu::)?spans?' = 'classmuu_1_1span.html'
'(?:muu::)?uint128_ts?' = 'group__core.html#gaa82164a62949a1b029695dff5441d577'
'(?:muu::)?int128_ts?' = 'group__core.html#gaf8e0aa5a37ec05e07c7b69077de9303c'
'(?:muu::)?float128_ts?' = 'group__core.html#ga74a70ec9e3331f37ebbc3e875e183861'
'(?:muu::)?bounding_box(?:es)?' = 'structmuu_1_1bounding__box.html'
'(?:muu::)?oriented_bounding_box(?:es)?' = 'structmuu_1_1oriented__bounding__box.html'
'(?:muu::)?planes?' = 'structmuu_1_1plane.html'
'(?:muu::)?quaternions?' = 'structmuu_1_1quaternion.html'
'(?:muu::)?vectors?' = 'structmuu_1_1vector.html'
