# this is a config file for Poxy - a Doxygen + m.css front-end written in Python.
# https://github.com/marzer/poxy

name                = 'muu'
author              = 'Mark Gillard'
description         = 'Miscellaneous useful utilities for C++'
cpp                 = 17
github              = 'marzer/muu'
license             = [ 'MIT', 'https://github.com/marzer/muu/blob/master/LICENSE' ]
show_includes       = true
logo                = 'images/logo.png'
favicon             = 'images/favicon.ico'
extra_files         = [
    'images/banner.png',
    'images/banner-small.png',
    'images/badge-gitter.svg',
    'images/badge-sponsor.svg',
]



[warnings]
enabled             = true
treat_as_errors     = false
undocumented        = false



[sources]
paths               = [ 'pages' ]
recursive_paths     = [ '../include' ]
patterns            = [ '*.h', '*.dox' ]
strip_paths         = [ '../include' ]



[images]
paths               = [ 'images' ]



[code_blocks]
types = [
    '[Mm]y_[a-zA-Z_]+',
    'virtual_base',
    'empty_parent',
    'nonempty_child',
    'thing_id',
    'thing_index',
]
macros = [ 'MUU_[A-Z0-9_]+?' ]



[implementation_headers]
'muu/chars.h' = [
    'muu/impl/unicode_char.h',
    'muu/impl/unicode_char16_t.h',
    'muu/impl/unicode_char32_t.h',
    'muu/impl/unicode_char8_t.h',
    'muu/impl/unicode_unsigned_char.h',
    'muu/impl/unicode_wchar_t.h'
]
'muu/core.h' = [
    'muu/impl/core_constants.h',
    'muu/impl/core_literals.h',
    'muu/impl/core_utils.h'
]
'muu/preprocessor.h' = [
    'muu/impl/preprocessor_for_each.h',
    'muu/impl/preprocessor_for_each_attributes.h',
]


[badges]
'1. CI'     = [
    'https://github.com/marzer/muu/actions/workflows/ci.yaml/badge.svg?branch=master',
    'https://github.com/marzer/muu/actions/workflows/ci.yaml'
]
'2. Sponsor'        = [
    'badge-sponsor.svg',
    'https://github.com/sponsors/marzer'
 ]
'3. Gitter'        = [
    'badge-gitter.svg',
    'https://gitter.im/marzer/muu'
 ]




[autolinks]
'(?:muu::)?bounding[ _]box(?:es)?' = 'structmuu_1_1bounding__box.html'
'(?:muu::)?bounding[ _]sphere(?:s)?' = 'structmuu_1_1bounding__sphere.html'
'(?:muu::)?float128_ts?' = 'group__core.html#ga74a70ec9e3331f37ebbc3e875e183861'
'(?:muu::)?halfs?(?!-)' = 'structmuu_1_1half.html'
'(?:muu::)?int128_ts?' = 'group__core.html#gaf8e0aa5a37ec05e07c7b69077de9303c'
'(?:muu::)?line[ _]segments?' = 'structmuu_1_1line__segment.html'
'(?:muu::)?matri(?:x|ces)?' = 'structmuu_1_1matrix.html'
'(?:muu::)?oriented[ _]bounding[ _]box(?:es)?' = 'structmuu_1_1oriented__bounding__box.html'
'(?:muu::)?planes?' = 'structmuu_1_1plane.html'
'(?:muu::)?quaternions?' = 'structmuu_1_1quaternion.html'
'(?:muu::)?spans?' = 'classmuu_1_1span.html'
'(?:muu::)?string_params?' = 'classmuu_1_1string__param.html'
'(?:muu::)?strong[ _]typedef(?:s)?' = 'structmuu_1_1strong__typedef.html'
'(?:muu::)?strong[ _]typedef[ _]trait(?:s)?' = 'namespacemuu_1_1strong__typedef__traits.html'
'(?:muu::)?static[ _]strings?' = 'classmuu_1_1static__string.html'
'(?:muu::)?triangles?' = 'structmuu_1_1triangle.html'
'(?:muu::)?uint128_ts?' = 'group__core.html#gaa82164a62949a1b029695dff5441d577'
'(?:muu::)?vectors?' = 'structmuu_1_1vector.html'
