# this is a config file for Poxy - a Doxygen + m.css front-end written in Python.
# https://github.com/marzer/poxy

name                = 'muu'
description         = 'Miscellaneous useful utilities for C++'
cpp                 = 17
github              = 'marzer/muu'
license             = [ 'MIT', 'https://github.com/marzer/muu/blob/master/LICENSE' ]
show_includes       = true
generate_tagfile    = true
logo                = 'images/logo.png'
favicon             = 'images/favicon.ico'
extra_files         = [
	'images/banner.png',
	'images/banner-small.png',
]



[warnings]
enabled             = true
treat_as_errors     = false
undocumented        = false



[sources]
paths               = [ 'pages' ]
recursive_paths     = [ '../include' ]
patterns            = [ '*.h', '*.dox' ]
strip_paths         = [ '../include' ]



[images]
paths               = [ 'images' ]



[code_blocks]
types = [
	'[Mm]y_[a-zA-Z_]+',
	'virtual_base',
	'empty_parent',
	'nonempty_child',
	'immovable',
	'uncopyable'
]
macros = [ 'MUU_[A-Z0-9_]+?' ]
string_literals = [ '_uuid' ]
numeric_literals = [
	'_sz',
	'_[kmg]?b',
	'_[iu](?:8|16|32|64|128)',
	'_f16',
]



[implementation_headers]
'muu/preprocessor.h' = [
	'muu/impl/preprocessor_for_each.h'
]
'muu/core.h' = [
	'muu/impl/core_bit.h',
	'muu/impl/core_build.h',
	'muu/impl/core_constants.h',
	'muu/impl/core_literals.h',
	'muu/impl/core_meta.h',
	'muu/impl/core_utils.h'
]
'muu/chars.h' = [
	'muu/impl/unicode_char.h',
	'muu/impl/unicode_char16_t.h',
	'muu/impl/unicode_char32_t.h',
	'muu/impl/unicode_char8_t.h',
	'muu/impl/unicode_unsigned_char.h',
	'muu/impl/unicode_wchar_t.h'
]



[badges]
'CircleCI' = [ 'https://circleci.com/gh/marzer/muu.svg?style=shield', 'https://circleci.com/gh/marzer/muu' ]
