// This file is a part of muu and is subject to the the terms of the MIT license.
// Copyright (c) Mark Gillard <mark.gillard@outlook.com.au>
// See https://github.com/marzer/muu/blob/master/LICENSE for the full license text.
// SPDX-License-Identifier: MIT
#pragma once

/// \file
/// \brief		Convenience header for including _all_ other muu headers.

#include "accumulator.h"
#include "axis_angle.h"
#include "bit.h"
#include "blob.h"
#include "bounding_box.h"
#include "chars.h"
#include "compressed_pair.h"
#include "core.h"
#include "emplacement_array.h"
#include "euler_angles.h"
#include "function_view.h"
#include "generic_allocator.h"
#include "half.h"
#include "hashing.h"
#include "integer_range.h"
#include "iterators.h"
#include "line_segment.h"
#include "math.h"
#include "matrix.h"
#include "meta.h"
#include "oriented_bounding_box.h"
#include "plane.h"
#include "quaternion.h"
#include "scope_guard.h"
#include "span.h"
#include "static_string.h"
#include "string_param.h"
#include "strings.h"
#include "strong_typedef.h"
#include "tagged_ptr.h"
#include "thread_pool.h"
#include "triangle.h"
#include "type_list.h"
#include "type_name.h"
#include "uuid.h"
#include "vector.h"
#include "packed_unit_vector.h"
//#include "bitset.h"
//#include "bounding_sphere.h"
//#include "concatenate.h"
//#include "rolling_average.h"
//#include "semver.h"
