// This file is a part of muu and is subject to the the terms of the MIT license.
// Copyright (c) Mark Gillard <mark.gillard@outlook.com.au>
// See https://github.com/marzer/muu/blob/master/LICENSE for the full license text.
// SPDX-License-Identifier: MIT
#pragma once

/// \file
/// \brief		Convenience header for including _all_ other muu headers.

#include "accumulator.h"
#include "aligned_alloc.h"
#include "apply_alignment.h"
#include "assume_aligned.h"
#include "axis_angle.h"
#include "bit.h"
#include "bit_cast.h"
#include "bit_ceil.h"
#include "bit_fill.h"
#include "bit_floor.h"
#include "bit_pack.h"
#include "blob.h"
#include "bounding_box.h"
#include "bounding_sphere.h"
#include "build.h"
#include "byte_reverse.h"
#include "chars.h"
#include "compressed_pair.h"
#include "core.h"
#include "countl.h"
#include "countr.h"
#include "emplacement_array.h"
#include "euler_angles.h"
#include "for_sequence.h"
#include "function_view.h"
#include "half.h"
#include "hashing.h"
#include "integer_literals.h"
#include "integral_range.h"
#include "is_constant_evaluated.h"
#include "iterators.h"
#include "launder.h"
#include "line_segment.h"
#include "math.h"
#include "matrix.h"
#include "meta.h"
#include "oriented_bounding_box.h"
#include "packed_unit_vector.h"
#include "pause.h"
#include "plane.h"
#include "pointer_cast.h"
#include "popcount.h"
#include "quaternion.h"
#include "scope_guard.h"
#include "size_t_literals.h"
#include "span.h"
#include "spin_mutex.h"
#include "static_array.h"
#include "static_string.h"
#include "string_param.h"
#include "strings.h"
#include "strong_typedef.h"
#include "tagged_ptr.h"
#include "thread_name.h"
#include "thread_pool.h"
#include "triangle.h"
#include "type_list.h"
#include "type_name.h"
#include "utf_decode.h"
#include "utf8_decoder.h"
#include "utf16_decoder.h"
#include "uuid.h"
#include "vector.h"
//#include "bitset.h"
//#include "bounding_sphere.h"
//#include "concatenate.h"
//#include "rolling_average.h"
//#include "semver.h"
